#!/usr/bin/with-contenv bash

set -o pipefail

# Exit handler
onExit() {
    local exitCode="$?"
    local pid

    # Kill the backup process
    pid="$(cat /var/run/backupd.pid 2>/dev/null)"
    if [ -n "${pid}" ]; then
        kill -TERM "${pid}" 2>/dev/null
    fi

    exit "${exitCode}"
}

main() {
    local pid

    /app/backup &
    pid=$!

    printf "%s" "${pid}" >/var/run/backupd.pid

    # Wait for the backup process to finish
    wait "${pid}"

    rm -rf /var/run/backupd.pid
}

trap onExit EXIT
main
