#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -eo pipefail

# init-crontab main
main() {
    exec > >(while read line; do echo "[init-crontab] ${line}"; done) 2>&1

    echo "Creating crontab file for user ${PUID:-911}..."
    echo "- Schedule: ${CRONTAB_EXPRESSION:?}"

    echo "${CRONTAB_EXPRESSION:?} /app/run" >>/etc/crontabs/abc
}
main
