#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -o pipefail

# svc-housekeeper main
main() {
    # This will prepend service name to all output from here
    exec > >(while read line; do echo "[svc-housekeeper] ${line}"; done) 2>&1

    printf "Service started\n"

    local pid

    while true; do
        /app/housekeeper &
        pid="$!"
        printf "%s" "${pid}" >/var/run/housekeeperd.pid
        sleep 30

        # Make sure the process is actually finished before continuing
        wait "${pid}"
        rm -f "/var/run/housekeeperd.pid"
    done
}

main
